// <auto-generated />
using GuyubApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuyubApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190504101805_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("GuyubApp.API.Models.RW", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kecamatan");

                    b.Property<string>("Kelurahan");

                    b.Property<string>("Keterangan");

                    b.Property<string>("Kota");

                    b.Property<string>("Nama");

                    b.Property<string>("Provinsi");

                    b.HasKey("Id");

                    b.ToTable("RWs");
                });
#pragma warning restore 612, 618
        }
    }
}
